# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      -main
  pull_request:
      branches:
        -main
  workflow_dispatch:
      
jobs:
  check_bats_version:
    name: first step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gcc main.c
      - run: ./a.out
