name: CI example

env:
  EXECUTABLES: CI
  MIRROR_URL: git@github.com:EpitechPromo2026/B-DOP-200-MPL-2-1-chocolatine-matheo.beaunez.git

on: [push, delete]

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          files=$(find -name "*~" -or -name  -or -name "#*#" -or -name "*.o" -or -name "*.a" -or -name "*.so" -or -name "*.gcno" -or -name "*.gcda" -or -name "*.gcov" -or -wholename "*/tmp/*")
          if [ -n "$files" ];then
            for file in $files;do
              echo "Unwanted file detected: $file"
            done
            echo "Checks if the repository is clean and void of any unwanted files (temp files, binary files, ect.)"
            exit 1
          fi
  check_program_compilation:
    needs: [check_repository_cleanliness]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2
      - run: make
      - run: make clean
      - run: |
          find -name $(EXECUTABLES)
  push_to_mirror:
    needs: [check_repository_cleanliness, check_program_compilation]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: $(MIRROR_URL)
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
