# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      -main
  pull_request:
      branches:
        -main
  workflow_dispatch:
      
jobs:
  run:
    runs-on: ubuntu-18.04
